version: '2'
services:
    nudgun-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/nudgun/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=nudgun
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
